services:
  database-docker:
    image: postgres:17-alpine
    container_name: database-docker
    restart: always
    env_file:
      - docker.env
    ports:
      - 5440:5432
    volumes:
      - postgres_data-docker:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - envocc-card

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - envocc-card
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3000
    depends_on:
      - database-docker
    networks:
      - envocc-card
    env_file:
      - docker.env
    volumes:
      - ./assets:/app/assets
    command: |
      sh -c "
        bun prisma migrate deploy
        bun prisma db seed
        bun run start:prod
      "
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:3000/envocc-card/api/v2/']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
volumes:
  postgres_data-docker:
  postgres_data-local:
networks:
  envocc-card:
    driver: bridge
